### ISSUE TITLE
disparcher container fails to start due to incorrect dispatcher reference

### ISSUE THREAD

**Issue by znikolovski** [AdobeAtAdobe/aem_6-1_docker#1]
At first the dispatcher container was failing as it was referencing /aem/dispatcher/module/dispatcher-apache2.4-4.1.10.so and failing to find the file. Upon inspecting the logs I discovered that when unpacking the dispatcher tar.gz with version 4.1.9 the .so file was actually 4.1.11.

After correcting the /dispatcher-ps/resources/mods-available/dispatcher.load file to point to version 4.1.11 the issue is that the downloaded file is a 32bit version, even though the download url is https://www.adobeaemcloud.com/content/companies/public/adobe/dispatcher/dispatcher/_jcr_content/top/download_8/file.res/dispatcher-apache2.4-linux-x86-64-4.1.9.tar.gz

**Comment by znikolovski** [comment]
I resolved this issue by changing the url in Dockerfile to point to https://www.adobeaemcloud.com/content/companies/public/adobe/dispatcher/dispatcher/_jcr_content/top/download_10/file.res/dispatcher-apache2.4-linux-x86-64-4.1.11.tar.gz

**Comment by dbenge** [comment]
I will patch that up...

**Comment by znikolovski** [comment]
Thanks David!
Other than that hiccup everything works as expected.

**Comment by dbenge** [comment]
Excelect to hear.  I have not got a ton of feedback yet so thanks for your help.

**Comment by znikolovski** [comment]
No worries! I'll be playing around with this a bit so will provide some feedback as I go.
Off topic for this ticket but I had a look at obtaining the IP for the containers that AEM and dispatcher run on. 
I'm using Docker Toolbox rather than boot2docker which comes with a docker-machine utility which gives me the IP of the virtual box that hosts the containers:

```
bash-3.2$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM
default   *        virtualbox   Running   tcp://192.168.99.100:2376
```

Maybe that can help with providing the URLs to access the instances as part of the composer action?

**Comment by dbenge** [comment]
That sounds nice.  I will give that a try.
