### ISSUE TITLE
If no addition packages then images don't build

### ISSUE THREAD

**Issue by ghost** [AdobeAtAdobe/aem_6-1_docker#13]
The docker image build will not continue beyond this line when you have no zip packages in the /resource/packages folder
`ADD resources/packages/*.zip /aem/packages/`

We should make this also work if no packages need to be installed

**Comment by dbenge** [comment]
Good point.  Make that change and do a pull request for us to review.

**Comment by ghost** [comment]
according to the docker spec it is not possible to work around this.
