### ISSUE TITLE
Adding a friendly compose script

### ISSUE THREAD

**Issue by znikolovski** [AdobeAtAdobe/aem_6-1_docker#2]
We could add a start-container.sh script to the composedev-tar folder:

```
#!/bin/bash 
docker-compose up -d;
HTTP=$(docker-machine ls | egrep -o 'tcp://[^:]*' | sed 's/tcp:/http:/');
echo "AEM Author URL: $HTTP:4502";
echo "AEM Publish URL: $HTTP:4503";
echo "Dispatcher URL: $HTTP";
```

This will run search for the IP of the docker-machine running the containers and print out friendly messages with the access urls for AEM/Dispatcher

**Comment by dbenge** [comment]
you want to help contribute? Looks like good changes to me.

**Comment by znikolovski** [comment]
Absolutely! :)

**Comment by dbenge** [comment]
merged
